export const userData = [
    {
        id: 1,
        img: '/images/faces/face1.jpg',
        name: 'Danny Santiago',
        place: 'San Francisco, California',
        pro: true,
        views: '23455',
        icons: ['mdi mdi-check-circle-outline icon-sm', 'mdi mdi-email-outline icon-sm', 'mdi mdi-format-list-bulleted icon-sm'],
        progress: '67',
        progressColor: 'success',
        traffic: '350,897',
        users: '2,356',
        sales: '927',
        performance: '49.65',
        profileimgs: []
    },
    {
        id: 2,
        img: '/images/faces/face2.jpg',
        name: 'Lelia Bowers',
        place: 'Central African Republic',
        pro: false,
        views: '23525',
        icons: ['mdi mdi-check-circle-outline icon-sm', 'mdi mdi-email-outline icon-sm', 'mdi mdi-email-outline icon-sm'],
        progress: '45',
        progressColor: 'info',
        traffic: '443,235',
        users: '3,433',
        sales: '345',
        performance: '34.43',
        profileimgs: []
    },
    {
        id: 3,
        img: '/images/faces/face3.jpg',
        name: 'Tommy Jenkins',
        place: 'Bouvet Island',
        pro: false,
        views: '34526',
        icons: ['mdi mdi-check-circle-outline icon-sm', 'mdi mdi-email-outline icon-sm', 'mdi mdi-format-list-bulleted icon-sm'],
        progress: '77',
        progressColor: 'danger',
        traffic: '563,645',
        users: '2,543',
        sales: '765',
        performance: '23.56',
        profileimgs: []
    },
    {
        id: 4,
        img: '/images/faces/face6.jpg',
        name: 'Ramiz Dedaković',
        place: 'Saint Kitts and Nevis',
        pro: false,
        views: '69434',
        icons: ['mdi mdi-check-circle-outline icon-sm', 'mdi mdi-email-outline icon-sm', 'mdi mdi-email-outline icon-sm'],
        progress: '55',
        progressColor: 'warning',
        traffic: '343,525',
        users: '5,324',
        sales: '235',
        performance: '45.23',
        profileimgs: []
    },
]
