# Generated by Django 5.2.1 on 2025-05-30 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appliance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "watt_hour_per_hour",
                    models.FloatField(help_text="Energy usage per hour (Wh)"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest_id", models.CharField(max_length=100)),
                ("hours_per_day", models.FloatField()),
                (
                    "appliance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.appliance"
                    ),
                ),
            ],
        ),
    ]
