# Generated by Django 5.2.1 on 2025-06-23 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("label", models.CharField(max_length=100)),
                (
                    "emission_factor_yen",
                    models.FloatField(
                        help_text="Emission factor per ¥100,000 spent (kg CO₂e)"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShoppingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest_id", models.CharField(max_length=100)),
                ("price_yen", models.FloatField(help_text="Price per item in ¥")),
                ("quantity", models.PositiveIntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.category"
                    ),
                ),
            ],
        ),
    ]
