# Generated by Django 5.2 on 2025-06-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_shoppingrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=50)),
                ('distance_km', models.FloatField(help_text='Distance travelled in kilometers')),
            ],
        ),
    ]
